package ch.fortysix.maven.plugin


import ch.fortysix.maven.plugin.sender.support.SurefireReport;
import ch.fortysix.maven.plugin.sender.support.TaglistReport;
import ch.fortysix.maven.plugin.sender.PostmanReportSender;

import ch.fortysix.maven.plugin.sender.SurefireReportSender;
import ch.fortysix.maven.plugin.sender.TaglistReportSender;

import java.io.File;

import org.codehaus.gmaven.mojo.GroovyMojo;

/**
 * Sends the mails/reports collected by the 'collect' goal.
 *
 * @goal send
 */
class MailMojo extends GroovyMojo {
	
	
	/**
	 * @parameter expression="${project}"
	 * @required
	 * @readonly
	 */
	org.apache.maven.project.MavenProject project
	
	/**
	 * The xml file to read the postman report from.
	 * @parameter default-value="${project.build.directory}/postman.xml"
	 */
	File reportFile;
	
	/**
	 * Email subject line. 
	 * @parameter expression="${subject}" default-value="postman has a delivery"
	 */
	String subject;
	
	/**
	 * Email address of sender.
	 * @parameter expression="${from}" 
	 * @required
	 */
	String from;
	
	/**
	 * flag to indicate whether to halt the build on any error. The default value is true.
	 * @parameter default-value="true"
	 */
	boolean failonerror = true;
	
	/**
	 * Host name of the SMTP server. The default value is localhost.
	 * @parameter expression="${mailhost}" default-value="localhost"
	 */
	String mailhost;
	
	/**
	 * TCP port of the SMTP server. The default value is 25.
	 * @parameter expression="${mailport}" default-value="25"
	 */
	String mailport;
	
	/**
	 * User name for SMTP auth
	 * @parameter 
	 */
	String mailuser
	
	/**
	 * Password for SMTP auth
	 * @parameter 
	 */
	String mailpassword
	
	/**
	 * <pre>
	 * <taglistReport>								
	 * 	<tagClasses>
	 * 		<tagClass>
	 * 			<displayName>TODO Work</displayName>
	 * 	 		<receivers>	 
	 * 		  		<receiver>developerId</receiver>
	 * 		  		<receiver>sam@topland.com</receiver>
	 * 	 		</receivers>
	 * 		</tagClass>
	 * 	</tagClasses>
	 * </taglistReport>
	 * </pre>
	 * @parameter 
	 */	
	TaglistReport taglistReport;
	
	/**
	 * The generated taglist report (previously generated by 'taglist-maven-plugin'). 
	 * @parameter default-value="${project.build.directory}/taglist/taglist.xml"
	 */
	File taglistReportXml;
	
	/**
	 * Indicates whether you need TLS/SSL
	 * @parameter  default-value="false"
	 */
	boolean mailssl	= false
	
	/**
	 * Base directory where all surefire test reports are read from.  
	 * @parameter expression="${project.build.directory}/surefire-reports" default-value="${project.build.directory}/surefire-reports"
	 */	
	File testReportsDirectory
	
	/**
	 * Default value for 'reportFilePattern'="TEST-.*.xml" 
	 * <pre>
	 * 		<surefireReport>
	 * 			<reportFilePattern>="TEST-.*.xml</reportFilePattern>
	 * 	 		<receivers>	 
	 * 		  		<receiver>developerId</receiver>
	 * 		  		<receiver>sam@topland.com</receiver>
	 * 	 		</receivers>
	 * 		</surefireReport>
	 * </pre>
	 * @parameter 
	 */	
	SurefireReport surefireReport;	
	
	void execute() {
		
		PostmanReportSender sender = new PostmanReportSender(log: getLog())
		def receiver2Rules = sender.getMails(reportFile)
		receiver2Rules.each sendReport
		
		TaglistReportSender taglistSender = new TaglistReportSender(log: getLog(), taglistReport: taglistReport)
		def receiver2Taglist = taglistSender.getMails(taglistReportXml)
		receiver2Taglist.each sendReport
		
		SurefireReportSender testReportSender = new SurefireReportSender(log: getLog(), surefireReport: surefireReport)
		def receiver2TestReport = testReportSender.getMails(testReportsDirectory)
		receiver2TestReport.each sendReport
		
	}
	
	/**
	 * Sends one mail
	 */
	def sendReport = { receiver, mailContent ->
		
		def address = ""
		
		if(!receiver.contains("@")){
			def email = project.developers?.find {  
				it.id == receiver
			}?.email
			if(email){
				getLog().info "replace [$receiver] by [$email]"
				receiver = email
			}else{
				getLog().warn "not able to find email for [$receiver]"
			}
		}
		getLog().info "send mail to: $receiver"
		
		def message = mailContent.asMailBody()
		
		println message
		if(getLog().isDebugEnabled()){
			
		}
		
		def tos = [receiver]
		MailSender sender = new MailSender(from: from, 
		subject: subject, 
		message: message, 
		mailhost: mailhost, 
		mailport: mailport, 
		failonerror: failonerror,
		ssl: mailssl,
		user: mailuser,
		password: mailpassword,
		receivers: tos)
		sender.sendMail()
	}	
	
}
