/**
 * 
 */
package ch.fortysix.maven.report;

import java.io.File;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Set;

import org.apache.maven.doxia.siterenderer.Renderer;
import org.apache.maven.project.MavenProject;
import org.apache.maven.reporting.MavenReportException;

import ch.fortysix.maven.report.surefire.SurefireReportBodyGenerator;
import ch.fortysix.maven.report.taglist.TaglistReportBodyGenerator;
import ch.fortysix.maven.report.taglist.TaglistReportSender;

/**
 * @author Domi
 * @goal postman-taglist-report
 * @phase site
 */
class PostmanTaglistReportMojo extends AbstractReportMojo {
	
	String getNlsPrefix(){
		"report.postman.taglist."
	}
	
	public String getOutputName() {
		"postman-taglist-report"
	}	
	
	//	/**
	//	 * Who should receive a mail? One can use an id of a developer registered in the pom or an email address directly.
	//	 * <pre>
	//	 * 	 		&lt;receivers&gt;	 
	//	 * 		  		&lt;receiver&gt;developerId&lt;/receiver&gt;
	//	 * 		  		&lt;receiver&gt;sam@topland.com&lt;/receiver&gt;
	//	 * 	 		&lt;/receivers&gt;
	//	 * </pre>
	//	 * @parameter 
	//	 * @required
	//	 */	
	//	Set receivers;	
	
	/**
	 * The generated taglist report (previously generated by 'taglist-maven-plugin'). 
	 * @parameter default-value="${project.build.directory}/taglist/taglist.xml"
	 */
	File taglistReportXml;
	
	/**
	 * Maps the tag class (from taglist plugin) to a list of receivers.
	 * Who should receive a mail? One can use an id of a developer registered in the pom or an email address directly.
	 * <pre>
	 * 								&lt;tagClasses&gt;
	 * 									&lt;tagClass&gt;
	 * 										&lt;displayName&gt;Todo Work&lt;/displayName&gt;
	 * 										&lt;receivers&gt;
	 * 											&lt;receiver&gt;developerId&lt;/receiver&gt;
	 * 											&lt;receiver&gt;dude@xx.com&lt;/receiver&gt;
	 * 										&lt;/receivers&gt;
	 * 									&lt;/tagClass&gt;
	 * 								&lt;/tagClasses&gt; 
	 * </pre>
	 * @parameter 
	 * @required
	 */		
	List tagClasses = []
	
	void addTagClasse(TagClass tagClass){
		tagClasses.add(tagClass)
	}	
	
	protected void executeReport(Locale locale) throws MavenReportException {
		
		TaglistReportSender taglistSender = new TaglistReportSender(log: getLog(), tagClasses: tagClasses)
		def receiver2Mail = taglistSender.getMails(taglistReportXml)
		
		if(!skipMails){
			receiver2Mail.each sendReport
		} else{
			log.info "postamn skips sending mails!"
		}
		
		def report = new HtmlReporter(bodyGenerator: new TaglistReportBodyGenerator(receiver2TestReport: receiver2Mail))
		report.doGenerateReport( getBundle( locale ), getSink(), nlsPrefix, getLog() )
	}
	
	
}
